# Generated by Django 2.1.7 on 2019-04-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('score_ended', models.CharField(blank=True, max_length=5, null=True)),
                ('round', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='manager.Country')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('games', models.SmallIntegerField(blank=True, null=True)),
                ('goals', models.SmallIntegerField(blank=True, null=True)),
                ('assists', models.SmallIntegerField(blank=True, null=True)),
                ('goal_plus_pass', models.SmallIntegerField(blank=True, null=True)),
                ('yellow_cards', models.SmallIntegerField(blank=True, null=True)),
                ('red_cards', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statistic',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('score', models.SmallIntegerField()),
                ('president', models.CharField(blank=True, max_length=32, null=True)),
                ('coach', models.CharField(blank=True, max_length=32, null=True)),
                ('stadium', models.CharField(blank=True, max_length=64, null=True)),
                ('foundation', models.SmallIntegerField(blank=True, null=True)),
                ('site', models.URLField(blank=True, max_length=128, null=True, unique=True)),
                ('team_url', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='manager.Country')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=20, unique=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='manager.Country')),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.AddField(
            model_name='statistic',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='manager.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='manager.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='manager.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='manager.Tournament'),
        ),
    ]
